// tools/extensions/vs-code-extensions/files-and-folders-renamer/svelte/src/lib/components/NumberInput.svelte
<script lang="typescript">
	import { uid } from 'uid';

	export let value: number = null;
	export let label = '';
	export let required = false;

	export let id = `filled-text-field-${uid()}`;
	import { onMount } from 'svelte';
	import { MDCTextField } from '@material/textfield';
	let el;
	onMount(() => {
		const textField = new MDCTextField(el);
		textField.initialize();
	});
</script>

<label class="mdc-text-field mdc-text-field--filled" bind:this={el}>
	<span class="mdc-text-field__ripple" />
	<span class="mdc-floating-label" {id}>{label}</span>
	<input class="mdc-text-field__input" type="number" aria-labelledby={id} bind:value required={required} />
	<span class="mdc-line-ripple" />
</label>

// tools/extensions/vs-code-extensions/files-and-folders-renamer/solid/src/components/NumberInput.tsx
import { uid } from 'uid';

import { MDCTextField } from '@material/textfield';

import { Component, onMount } from "solid-js";
interface Props {
  value?;
  setValue?;
  label?;
  required?;
}


const NumberInput: Component<Props> = (props: Props) => {

  let id = `text-button-${uid()}`;
  let el;
  onMount(() => {

  })
  return (

    <label class="mdc-text-field mdc-text-field--filled" ref={el}>
      <span class="mdc-text-field__ripple" />
      <span class="mdc-floating-label" id={id}>{props.label}</span>
      <input class="mdc-text-field__input" type="number" aria-labelledby={id} value={props.value} required={props.required} />
      <span class="mdc-line-ripple" />
    </label>

  );
};

export default NumberInput;
