// languages/csharp/tools/extensions/vs-code-extensions/files-and-folders-renamer/solid/src/components/TextButton.tsx
import { uid } from 'uid';

import { MDCTextField } from '@material/textfield';

import { Component, onMount } from "solid-js";

interface Props {
  value?;
  setValue?;
  label?;
  required?;
  class?;
  onClick?;
  icon?;
  children?;
}

export const TextButton: Component<Props> = (props: Props) => {
  onMount(() => {

  })
  return (
    <button class="mdc-button" onClick={props.onClick}>
      <span class="mdc-button__ripple"></span>
      {props.icon}
      <span class="mdc-button__label">{props.children}</span>
    </button>
  );
};

// tools/extensions/vs-code-extensions/files-and-folders-renamer/svelte/src/lib/components/TextButton.svelte
<script>
    import { uid } from 'uid';

    export let value = '';

    let className= '';
    export {className as class};
    export let id = `text-button-${uid()}`;
</script>


<button class="mdc-button {className}" on:click>
  <span class="mdc-button__ripple"></span>
  <slot name="icon"/>
  <span class="mdc-button__label"><slot/></span>
</button>
